format_version: 10
pipelines:
  git-trigger:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-36b9022:
        git: https://github.com/Shalini3031/mybookstore.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - compile:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          git-trigger:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - succeed
                command: echo
                run_if: passed
